[general]
fontname=Monospace 10
selchars=-A-Za-z0-9,./?%&#:_
scrollback=1000
bgcolor=#282a36
fgcolor=#f8f8f2
palette_color_0=#21222c
palette_color_1=#ff5555
palette_color_2=#50fa7b
palette_color_3=#f1fa8c
palette_color_4=#bd93f9
palette_color_5=#ff79c6
palette_color_6=#8be9fd
palette_color_7=#f8f8f2
palette_color_8=#6272a4
palette_color_9=#ff6e6e
palette_color_10=#69ff94
palette_color_11=#ffb86c
palette_color_12=#d6acff
palette_color_13=#ff92df
palette_color_14=#a4ffff
palette_color_15=#ffffff
color_preset=Custom
disallowbold=false
cursorblinks=false
cursorunderline=false
audiblebell=false
visualbell=false
tabpos=top
geometry_columns=80
geometry_rows=24
hidescrollbar=false
hidemenubar=false
hideclosebutton=false
hidepointer=false
disablef10=false
disablealt=false
disableconfirm=false
