[*]
wallpaper_mode=color
wallpaper_common=1
desktop_bg=#282a36
desktop_fg=#f8f8f2
desktop_shadow=#282a36
desktop_font=Sans 12
show_wm_menu=0
sort=mtime;ascending;
show_documents=0
show_trash=0
show_mounts=0
